import { NextAuthProvider } from '@/app/providers'
import { Menu } from '@/components/menus/menu.components'
import type { Metadata } from 'next'
import { openSans } from './fonts'
import './globals.css'

export const metadata: Metadata = {
  title: "Where's my Teammate ?",
  description: 'Generated by create next app',
  viewport: 'width=device-width, initial-scale=1',
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="fr" className={`${openSans.variable}`}>
      <NextAuthProvider>
        <body className="min-h-screen w-screen pt-3 lg:flex lg:flex-col lg:items-center lg:gap-32">
          <header className="mb-14 px-2 flex flex-col gap-3 md:max-w-3xl lg:max-w-5xl xl:max-w-8xl">
            <h1 className="text-center">Where's my Teammate</h1>
            <Menu />
          </header>
          <main className="flex items-center justify-center w-full">
            <div className="px-2 pb-4 w-full md:max-w-3xl lg:max-w-5xl xl:max-w-8xl">{children}</div>
          </main>
        </body>
      </NextAuthProvider>
    </html>
  )
}
