import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { Card, CardBody, Center, Container, Wrap, Box, WrapItem, Button } from '@chakra-ui/react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  // fond beige, texte noir, titre jaune / rouge / orange,
  return (
    <>
      <Head>
        <title>Where's my BRO ?</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{ minHeight: '100vh', display: 'flex', alignItems: 'center' }}>
        <Container maxW="10xl" centerContent>
          <h1>Trouvez un BRO en quelques clics</h1>
          <h1>et soulevez de la fonte à la salle</h1>
          <Wrap direction={['row']} p="2px" justify="center">
            <WrapItem>
              <Card maxW="300px" h="300px">
                <CardBody>
                  <h2>Peur de faire un développé couché seul ?</h2>
                  <p>Ce temps est révolu car votre BRO sera là pour vous parer.</p>
                </CardBody>
              </Card>
            </WrapItem>
            <WrapItem>
              <Card maxW="300px" h="300px">
                <CardBody>
                  <h2>Vous n'arrivez pas à trouver un BRO aligné avec vos objectifs ?</h2>
                  <p>Prise de masse, session de force, perte de poids... Il y en a pour tous les goûts.</p>
                </CardBody>
              </Card>
            </WrapItem>
            <WrapItem>
              <Card maxW="300px" h="300px">
                <CardBody>
                  <h2>L'apéro du vendredi soir approche et votre volonté est sur le point de faillir ?</h2>
                  <p>Grâce à votre BRO, vous ne perdrez plus de vue vos objectifs.</p>
                </CardBody>
              </Card>
            </WrapItem>
          </Wrap>
          <p>Inscrivez-vous dès à présent et devenez plus fort que votre plus forte excuse.</p>
          <Button>S'inscrire</Button>
          <Button>Se connecter</Button>
          Dernières annonces:
        </Container>
      </div>
    </>
  )
}
