import Head from 'next/head'
import { signOut, useSession } from 'next-auth/react'
import { Presentation } from '@/components/Presentation'

export default function Home() {
  const { data: session } = useSession()

  // fond beige, texte noir, titre jaune / rouge / orange,
  return (
    <>
      <Head>
        <title>Where's my BRO ?</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        style={{
          minHeight: '100vh',
          display: 'flex',
          ...(session && { alignItems: 'center' }),
        }}
      >
        {session ? <button onClick={() => signOut()}>Sign out</button> : <Presentation />}
      </div>
    </>
  )
}
